### PR TITLE
[D3-345] multiple keys validation

### PR DESCRIPTION
**Pull request by oimou**
# Description
I made multiple keys validation working. I think that the largest changes are:

* Changed how to pass rules and a property's path to validate based on [the el-form's doc about dynamic form items](https://element.eleme.io/#/en-US/component/form#delete-or-add-form-items-dynamically) and [a relevant issue](https://github.com/ElemeFE/element/issues/2327).
* v-for with an array of private key objects so Vue can detect values' changes.

Also, I updated the "filled/quorum" indicator to count only valid inputs.

# How to check
1. `yarn serve` and open the app.
2. Go to an approval dialog and try some inputs.

# Screenshots
back-office

### CODE REVIEW

**Comment by laSinteZ** [comment]
Well, this is strange.
screen shot 2018-09-17 at 10 13 50
## How to repeat:
Setup script -> Login -> Wallets -> new transfer.

**Comment by oimou** [comment]
I will check it 🤔

**Comment by oimou** [comment]
I changed `beforeOpenApprovalDialog` to be called from either dialog.

**Comment by oimou** [comment]
I made a confirmation button become disabled if no keys are entered. I have only disabled the button but have kept its style as is because Robert is working on styling in another PR.

**Comment by laSinteZ** [comment]
Rebase please ^_^

**Pull request merged**
